export const DOMElements = {
    teamOne: document.getElementById('teamOne'),
    firstPlayer: document.getElementById('firstPlayer'),
    teamTwo: document.getElementById('teamTwo'),
    appContainer: document.getElementById('appContainer'),
    secondPlayer: document.getElementById('secondPlayer'),
    scoreOneDisplay: document.getElementById('scoreOne'),
    scoreTwoDisplay: document.getElementById('scoreTwo'),
    modal: document.getElementById('noteModal'),
    closeBtn: document.getElementsByClassName('close')[0],
    noteText: document.getElementById('noteText'),
    saveNoteBtn: document.getElementById('saveNote'),
    buttonDivOne: document.getElementById('buttonDivOne'),
    buttonDivTwo: document.getElementById('buttonDivTwo'),
    categoryInput: document.getElementById('categoryInput'),
    categoryButton: document.getElementById('categoryButton'),
    categoryList: document.getElementById('categoryList'),
    buttonSubmit: document.getElementById('buttonSubmit'),
    resetButton: document.getElementById('resetButton'),
    teamNames: document.getElementById('teamNames')
};